### ISSUE TITLE
TO-DO V-1.0.0

### ISSUE THREAD

**Issue by Whatever0rg** [Whatever0rg/AetherUnit#2]
# Mandetory
- [x] Make it write Data on SDCard
- [x] Make the format easy to import into excel or similar (.CSV)
- [x] Design a printable case
- [x] Make sure it's easy to start  (Idiotproof)
## Nice to have
- [ ] Make it expandable (substations for different rooms(V-2.0.0?))
- [ ] Add Read Out. LCD or LED or 7segment
- [x] A Logo for the Unit

**Comment by Whatever0rg** [comment]
Issue was closed, remaining Features will be added at in a later version.
